- name: Configure web servers
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create directory structure for web documents
      file:
        path: /web/html
        state: directory
        mode: '0755'

    - name: Copy nginx conf file to server
      copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Create link to nginx config file to enable it
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Generate index.html file from template
      template:
        src: ./templates/index.html.j2
        dest: /web/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reload nginx service
      service:
        name: nginx
        state: reloaded

    - name: enable nginx
      service:
        name: nginx
        enabled: true

